using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using Xunit;
using Xunit.Abstractions;
using RomanNumberConverter;
namespace TestRomanNumberConvert

{
    public class RomanNumberConvertUnitTest
    {
        private readonly INumberConverter _convert = new NumberConverter(); 
        private readonly ITestOutputHelper _output;
        public RomanNumberConvertUnitTest(ITestOutputHelper output)
        {
            _output = output;
        }

        [Fact]
        public void TestRomanToInt()
        {
            var success = true;
            int count = 0;
            foreach (var data in testData)
            {
                (int key, string error) = _convert.RomanToInt(data.Value);

                //Output acceptance test result for tester
                if (count < 3)
                {
                    count++;
                    _output.WriteLine($"{data.Value} Expected: {data.Key}, Result: {key}. ");
                }
                if (key == -1)
                {
                    _output.WriteLine($"'{data.Value}' is wrong format.");
                }
                //run throgh a long list, only output if there is error

                else if (key != data.Key)
                {
                    _output.WriteLine($"{data.Value} expected to be: {data.Key}, but the return value is {key}. Error message:{error} ");
                    success = false;
                }
            }
            Assert.True(success);
        }
        [Fact]
        public void TestIntToRoman()
        {
            var success = true;
            int count = 0;
            foreach (var data in testData)
            {
                string strRegex = @"[^IVXLCDM]|VV|LL|DD|[I]{4}|[X]{4}|[C]{4}|[M]{4}|IL|IC|ID|IM|VX|VL|VC|VD|VM|XD|XM|LC|LD|LM|DM|IIV|IIC|XXL|LLC|CCD|CCM";
                Regex regex = new Regex(strRegex);
                if (regex.IsMatch(data.Value))
                {
                    //Ignor data.value with wrong value.
                    continue;
                }
                (string value, string error) = _convert.IntToRoman(data.Key);

                //Output acceptance test result for tester
                if (count < 3)
                {
                    count++;
                    _output.WriteLine($"number: {data.Key} Expected: {data.Value}, Result: {value}.");
                }

                //run throgh a long list, only output if there is error
                if (value != data.Value.ToUpper())
                {
                    success = false;
                    _output.WriteLine($"number: {data.Key} expected to be: {data.Value}, but the return value is {value}. Error message:{error} ");
                }

            }
            Assert.True(success);

        }

        private Dictionary<int, string> testData
        {
            get
            {
                Dictionary<int, string> dic = new Dictionary<int, string>();
                dic.Add(1999, "MCMXCIX");
                dic.Add(2444, "MMCDXLIV");
                dic.Add(90, "XC");
                dic.Add(1111, "IIV");
                dic.Add(1112, "VV");
                dic.Add(1113, "IIIIII");
                dic.Add(1114, "DM");
                dic.Add(1, "I");
                dic.Add(2, "II");
                dic.Add(3, "III");
                dic.Add(4, "IV");
                dic.Add(5, "V");
                dic.Add(6, "VI");
                dic.Add(7, "VII");
                dic.Add(8, "VIII");
                dic.Add(9, "IX");
                dic.Add(10, "X");
                dic.Add(11, "XI");
                dic.Add(12, "XII");
                dic.Add(13, "XIII");
                dic.Add(14, "XIV");
                dic.Add(15, "XV");
                dic.Add(16, "XVI");
                dic.Add(17, "XVII");
                dic.Add(18, "XVIII");
                dic.Add(19, "XIX");
                dic.Add(20, "XX");
                dic.Add(21, "XXI");
                dic.Add(22, "XXII");
                dic.Add(23, "XXIII");
                dic.Add(24, "XXIV");
                dic.Add(25, "xxv");
                dic.Add(26, "XXVI");
                dic.Add(27, "XXVII");
                dic.Add(28, "XXVIII");
                dic.Add(29, "XXIX");
                dic.Add(30, "XXX");
                dic.Add(31, "XXXI");
                dic.Add(32, "XXXII");
                dic.Add(33, "XXXIII");
                dic.Add(34, "XXXIV");
                dic.Add(35, "XXXV");
                dic.Add(36, "XXXVI");
                dic.Add(37, "XXXVII");
                dic.Add(38, "XXXVIII");
                dic.Add(39, "XXXIX");
                dic.Add(40, "XL");
                dic.Add(41, "XLI");
                dic.Add(42, "XLII");
                dic.Add(43, "XLIII");
                dic.Add(44, "XLIV");
                dic.Add(45, "XLV");
                dic.Add(46, "XLVI");
                dic.Add(47, "XLVII");
                dic.Add(48, "XLVIII");
                dic.Add(49, "XLIX");
                dic.Add(50, "L");
                dic.Add(51, "LI");
                dic.Add(52, "LII");
                dic.Add(53, "LIII");
                dic.Add(54, "LIV");
                dic.Add(55, "LV");
                dic.Add(56, "LVI");
                dic.Add(57, "LVII");
                dic.Add(58, "LVIII");
                dic.Add(59, "LIX");
                dic.Add(60, "LX");
                dic.Add(61, "LXI");
                dic.Add(62, "LXII");
                dic.Add(63, "LXIII");
                dic.Add(64, "LXIV");
                dic.Add(65, "LXV");
                dic.Add(66, "LXVI");
                dic.Add(67, "LXVII");
                dic.Add(68, "LXVIII");
                dic.Add(69, "LXIX");
                dic.Add(70, "LXX");
                dic.Add(71, "LXXI");
                dic.Add(72, "LXXII");
                dic.Add(73, "LXXIII");
                dic.Add(74, "LXXIV");
                dic.Add(75, "LXXV");
                dic.Add(76, "LXXVI");
                dic.Add(77, "LXXVII");
                dic.Add(78, "LXXVIII");
                dic.Add(79, "LXXIX");
                dic.Add(80, "Lxxx");
                dic.Add(81, "LXXXI");
                dic.Add(82, "LXXXII");
                dic.Add(83, "LXXXIII");
                dic.Add(84, "LXXXIV");
                dic.Add(85, "LXXXV");
                dic.Add(86, "LXXXVI");
                dic.Add(87, "LXXXVII");
                dic.Add(88, "LXXXVIII");
                dic.Add(89, "LXXXIX");
                dic.Add(91, "XCI");
                dic.Add(92, "XCII");
                dic.Add(93, "XCIII");
                dic.Add(94, "XCIV");
                dic.Add(95, "XCV");
                dic.Add(96, "XCVI");
                dic.Add(97, "XCVII");
                dic.Add(98, "XCVIII");
                dic.Add(99, "XCIX");
                dic.Add(100, "C");
                dic.Add(101, "CI");
                dic.Add(102, "CII");
                dic.Add(103, "CIII");
                dic.Add(104, "CIV");
                dic.Add(105, "CV");
                dic.Add(106, "CVI");
                dic.Add(107, "CVII");
                dic.Add(108, "CVIII");
                dic.Add(109, "CIX");
                dic.Add(110, "CX");
                dic.Add(111, "CXI");
                dic.Add(112, "CXII");
                dic.Add(113, "CXIII");
                dic.Add(114, "CXIV");
                dic.Add(115, "CXV");
                dic.Add(116, "CXVI");
                dic.Add(117, "CXVII");
                dic.Add(118, "CXVIII");
                dic.Add(119, "CXIX");
                dic.Add(120, "CXX");
                dic.Add(121, "CXXI");
                dic.Add(122, "CXXII");
                dic.Add(123, "CXXIII");
                dic.Add(124, "CXXIV");
                dic.Add(125, "CXXV");
                dic.Add(126, "CXXVI");
                dic.Add(127, "CXXVII");
                dic.Add(128, "CXXVIII");
                dic.Add(129, "CXXIX");
                dic.Add(130, "CXXX");
                dic.Add(131, "CXXXI");
                dic.Add(132, "CXXXII");
                dic.Add(133, "CXXXIII");
                dic.Add(134, "CXXXIV");
                dic.Add(135, "CXXXV");
                dic.Add(136, "CXXXVI");
                dic.Add(137, "CXXXVII");
                dic.Add(138, "CXXXVIII");
                dic.Add(139, "CXXXIX");
                dic.Add(140, "CXL");
                dic.Add(141, "CXLI");
                dic.Add(142, "CXLII");
                dic.Add(143, "CXLIII");
                dic.Add(144, "CXLIV");
                dic.Add(145, "CXLV");
                dic.Add(146, "CXLVI");
                dic.Add(147, "CXLVII");
                dic.Add(148, "CXLVIII");
                dic.Add(149, "CXLIX");
                dic.Add(150, "CL");
                dic.Add(151, "CLI");
                dic.Add(152, "CLII");
                dic.Add(153, "CLIII");
                dic.Add(154, "CLIV");
                dic.Add(155, "CLV");
                dic.Add(156, "CLVI");
                dic.Add(157, "CLVII");
                dic.Add(158, "CLVIII");
                dic.Add(159, "CLIX");
                dic.Add(160, "CLX");
                dic.Add(161, "CLXI");
                dic.Add(162, "CLXII");
                dic.Add(163, "CLXIII");
                dic.Add(164, "CLXIV");
                dic.Add(165, "CLXV");
                dic.Add(166, "CLXVI");
                dic.Add(167, "CLXVII");
                dic.Add(168, "CLXVIII");
                dic.Add(169, "CLXIX");
                dic.Add(170, "CLXX");
                dic.Add(171, "CLXXI");
                dic.Add(172, "CLXXII");
                dic.Add(173, "CLXXIII");
                dic.Add(174, "CLXXIV");
                dic.Add(175, "CLXXV");
                dic.Add(176, "CLXXVI");
                dic.Add(177, "CLXXVII");
                dic.Add(178, "CLXXVIII");
                dic.Add(179, "CLXXIX");
                dic.Add(180, "CLXXX");
                dic.Add(181, "CLXXXI");
                dic.Add(182, "CLXXXII");
                dic.Add(183, "CLXXXIII");
                dic.Add(184, "CLXXXIV");
                dic.Add(185, "CLXXXV");
                dic.Add(186, "CLXXXVI");
                dic.Add(187, "CLXXXVII");
                dic.Add(188, "CLXXXVIII");
                dic.Add(189, "CLXXXIX");
                dic.Add(190, "CXC");
                dic.Add(191, "CXCI");
                dic.Add(192, "CXCII");
                dic.Add(193, "CXCIII");
                dic.Add(194, "CXCIV");
                dic.Add(195, "CXCV");
                dic.Add(196, "CXCVI");
                dic.Add(197, "CXCVII");
                dic.Add(198, "CXCVIII");
                dic.Add(199, "CXCIX");
                dic.Add(200, "CC");
                dic.Add(201, "CCI");
                dic.Add(202, "CCII");
                dic.Add(203, "CCIII");
                dic.Add(280, "CCLXXX");
                dic.Add(281, "CCLXXXI");
                dic.Add(282, "CCLXXXII");
                dic.Add(283, "CCLXXXIII");
                dic.Add(284, "CCLXXXIV");
                dic.Add(285, "CCLXXXV");
                dic.Add(286, "CCLXXXVI");
                dic.Add(287, "CCLXXXVII");
                dic.Add(288, "CCLXXXVIII");
                dic.Add(289, "CCLXXXIX");
                dic.Add(290, "CCXC");
                dic.Add(291, "CCXCI");
                dic.Add(292, "CCXCII");
                dic.Add(293, "CCXCIII");
                dic.Add(294, "CCXCIV");
                dic.Add(295, "CCXCV");
                dic.Add(296, "CCXCVI");
                dic.Add(297, "CCXCVII");
                dic.Add(298, "CCXCVIII");
                dic.Add(299, "CCXCIX");
                dic.Add(300, "CCC");
                dic.Add(331, "CCCXXXI");
                dic.Add(366, "CCCLXVI");
                dic.Add(367, "CCCLXVII");
                dic.Add(368, "CCCLXVIII");
                dic.Add(369, "CCCLXIX");
                dic.Add(370, "CCCLXX");
                dic.Add(371, "CCCLXXI");
                dic.Add(372, "CCCLXXII");
                dic.Add(373, "CCCLXXIII");
                dic.Add(374, "CCCLXXIV");
                dic.Add(375, "CCCLXXV");
                dic.Add(376, "CCCLXXVI");
                dic.Add(377, "CCCLXXVII");
                dic.Add(378, "CCCLXXVIII");
                dic.Add(379, "CCCLXXIX");
                dic.Add(380, "CCCLXXX");
                dic.Add(381, "CCCLXXXI");
                dic.Add(382, "CCCLXXXII");
                dic.Add(383, "CCCLXXXIII");
                dic.Add(384, "CCCLXXXIV");
                dic.Add(385, "CCCLXXXV");
                dic.Add(386, "CCCLXXXVI");
                dic.Add(387, "CCCLXXXVII");
                dic.Add(388, "CCCLXXXVIII");
                dic.Add(389, "CCCLXXXIX");
                dic.Add(390, "CCCXC");
                dic.Add(391, "CCCXCI");
                dic.Add(392, "CCCXCII");
                dic.Add(393, "CCCXCIII");
                dic.Add(394, "CCCXCIV");
                dic.Add(395, "CCCXCV");
                dic.Add(396, "CCCXCVI");
                dic.Add(397, "CCCXCVII");
                dic.Add(398, "CCCXCVIII");
                dic.Add(410, "CDX");
                dic.Add(411, "CDXI");
                dic.Add(412, "CDXII");
                dic.Add(413, "CDXIII");
                dic.Add(414, "CDXIV");
                dic.Add(415, "CDXV");
                dic.Add(416, "CDXVI");
                dic.Add(417, "CDXVII");
                dic.Add(418, "CDXVIII");
                dic.Add(419, "CDXIX");
                dic.Add(420, "CDXX");
                dic.Add(421, "CDXXI");
                dic.Add(422, "CDXXII");
                dic.Add(423, "CDXXIII");
                dic.Add(424, "CDXXIV");
                dic.Add(425, "CDXXV");
                dic.Add(426, "CDXXVI");
                dic.Add(427, "CDXXVII");
                dic.Add(428, "CDXXVIII");
                dic.Add(429, "CDXXIX");
                dic.Add(430, "CDXXX");
                dic.Add(431, "CDXXXI");
                dic.Add(432, "CDXXXII");
                dic.Add(433, "CDXXXIII");
                dic.Add(434, "CDXXXIV");
                dic.Add(435, "CDXXXV");
                dic.Add(436, "CDXXXVI");
                dic.Add(437, "CDXXXVII");
                dic.Add(438, "CDXXXVIII");
                dic.Add(439, "CDXXXIX");
                dic.Add(440, "CDXL");
                dic.Add(441, "CDXLI");
                dic.Add(442, "CDXLII");
                dic.Add(443, "CDXLIII");
                dic.Add(444, "CDXLIV");
                dic.Add(445, "CDXLV");
                dic.Add(446, "CDXLVI");
                dic.Add(447, "CDXLVII");
                dic.Add(448, "CDXLVIII");
                dic.Add(467, "CDLXVII");
                dic.Add(468, "CDLXVIII");
                dic.Add(469, "CDLXIX");
                dic.Add(470, "CDLXX");
                dic.Add(471, "CDLXXI");
                dic.Add(472, "CDLXXII");
                dic.Add(473, "CDLXXIII");
                dic.Add(474, "CDLXXIV");
                dic.Add(476, "CDLXXVI");
                dic.Add(478, "CDLXXVIII");
                dic.Add(479, "CDLXXIX");
                dic.Add(480, "CDLXXX");
                dic.Add(481, "CDLXXXI");
                dic.Add(482, "CDLXXXII");
                dic.Add(483, "CDLXXXIII");
                dic.Add(484, "CDLXXXIV");
                dic.Add(485, "CDLXXXV");
                dic.Add(486, "CDLXXXVI");
                dic.Add(487, "CDLXXXVII");
                dic.Add(488, "CDLXXXVIII");
                dic.Add(489, "CDLXXXIX");
                dic.Add(490, "CDXC");
                dic.Add(491, "CDXCI");
                dic.Add(492, "CDXCII");
                dic.Add(493, "CDXCIII");
                dic.Add(494, "CDXCIV");
                dic.Add(495, "CDXCV");
                dic.Add(496, "CDXCVI");
                dic.Add(497, "CDXCVII");
                dic.Add(498, "CDXCVIII");
                dic.Add(499, "CDXCIX");
                dic.Add(500, "D");
                dic.Add(501, "DI");
                dic.Add(517, "DXVII");
                dic.Add(518, "DXVIII");
                dic.Add(519, "DXIX");
                dic.Add(520, "DXX");
                dic.Add(521, "DXXI");
                dic.Add(522, "DXXII");
                dic.Add(523, "DXXIII");
                dic.Add(524, "DXXIV");
                dic.Add(525, "DXXV");
                dic.Add(526, "DXXVI");
                dic.Add(527, "DXXVII");
                dic.Add(528, "DXXVIII");
                dic.Add(529, "DXXIX");
                dic.Add(530, "DXXX");
                dic.Add(531, "DXXXI");
                dic.Add(532, "DXXXII");
                dic.Add(533, "DXXXIII");
                dic.Add(534, "DXXXIV");
                dic.Add(536, "DXXXVI");
                dic.Add(537, "DXXXVII");
                dic.Add(538, "DXXXVIII");
                dic.Add(539, "DXXXIX");
                dic.Add(540, "DXL");
                dic.Add(541, "DXLI");
                dic.Add(542, "DXLII");
                dic.Add(543, "DXLIII");
                dic.Add(544, "DXLIV");
                dic.Add(545, "DXLV");
                dic.Add(546, "DXLVI");
                dic.Add(547, "DXLVII");
                dic.Add(548, "DXLVIII");
                dic.Add(549, "DXLIX");
                dic.Add(550, "DL");
                dic.Add(551, "DLI");
                dic.Add(584, "DLXXXIV");
                dic.Add(585, "DLXXXV");
                dic.Add(586, "DLXXXVI");
                dic.Add(587, "DLXXXVII");
                dic.Add(588, "DLXXXVIII");
                dic.Add(589, "DLXXXIX");
                dic.Add(590, "DXC");
                dic.Add(591, "DXCI");
                dic.Add(592, "DXCII");
                dic.Add(593, "DXCIII");
                dic.Add(594, "DXCIV");
                dic.Add(595, "DXCV");
                dic.Add(596, "DXCVI");
                dic.Add(597, "DXCVII");
                dic.Add(598, "DXCVIII");
                dic.Add(599, "DXCIX");
                dic.Add(600, "DC");
                dic.Add(601, "DCI");
                dic.Add(602, "DCII");
                dic.Add(603, "DCIII");
                dic.Add(613, "DCXIII");
                dic.Add(614, "DCXIV");
                dic.Add(615, "AD XV");
                dic.Add(616, "ADXVI");
                dic.Add(617, "ADXVII");
                dic.Add(618, "ADXVIII");
                dic.Add(619, "ADXIX");
                dic.Add(620, "DCXX");
                dic.Add(621, "DCXXI");
                dic.Add(622, "ADXXII");
                dic.Add(623, "AD XXIII");
                dic.Add(624, "DCXXIV");
                dic.Add(625, "DCXXV");
                dic.Add(626, "DCXXVI");
                dic.Add(627, "ADXXVII");
                dic.Add(628, "ADXXVIII");
                dic.Add(629, "DCXXIX");
                dic.Add(630, "DCXXX");
                dic.Add(631, "DCXXXI");
                dic.Add(632, "DCXXXII");
                dic.Add(633, "DCXXXIII");
                dic.Add(634, "DCXXXIV");
                dic.Add(635, "DCXXXV");
                dic.Add(636, "DCXXXVI");
                dic.Add(637, "DCXXXVII");
                dic.Add(638, "ADXXXVIII");
                dic.Add(639, "DCXXXIX");
                dic.Add(640, "DCXL");
                dic.Add(641, "DCXLI");
                dic.Add(642, "DCXLII");
                dic.Add(643, "DCXLIII");
                dic.Add(644, "DCXLIV");
                dic.Add(645, "DCXLV");
                dic.Add(646, "DCXLVI");
                dic.Add(647, "DCXLVII");
                dic.Add(648, "DCXLVIII");
                dic.Add(649, "DCXLIX");
                dic.Add(650, "DCL");
                dic.Add(651, "DCLI");
                dic.Add(652, "DCLII");
                dic.Add(653, "DCL III");
                dic.Add(654, "DCLIV");
                dic.Add(655, "DCLV");
                dic.Add(656, "DCLVI");
                dic.Add(657, "DCLVII");
                dic.Add(658, "DCLVIII");
                dic.Add(659, "DCLIX");
                dic.Add(660, "DCLX");
                dic.Add(661, "DCLXI");
                dic.Add(662, "DCLXII");
                dic.Add(663, "DCLXIII");
                dic.Add(664, "DCLXIV");
                dic.Add(665, "DCLXV");
                dic.Add(666, "DCLXVI");
                dic.Add(667, "DCLXVII");
                dic.Add(668, "DCLXVIII");
                dic.Add(669, "DCLXIX");
                dic.Add(728, "DCCXXVIII");
                dic.Add(729, "DCCXXIX");
                dic.Add(730, "DCCXXX");
                dic.Add(731, "DCCXXXI");
                dic.Add(732, "DCCXXXII");
                dic.Add(733, "DCCXXXIII");
                dic.Add(734, "DCCXXXIV");
                dic.Add(735, "DCCXXXV");
                dic.Add(736, "DCCXXXVI");
                dic.Add(737, "DCCXXXVII");
                dic.Add(738, "DCCXXXVIII");
                dic.Add(739, "DCCXXXIX");
                dic.Add(740, "DCCXL");
                dic.Add(741, "DCCXLI");
                dic.Add(742, "DCCXLII");
                dic.Add(743, "DCCXLIII");
                dic.Add(744, "DCCXLIV");
                dic.Add(745, "DCCXLV");
                dic.Add(746, "DCCXLVI");
                dic.Add(747, "DCCXLVII");
                dic.Add(748, "DCCXLVIII");
                dic.Add(749, "DCCXLIX");
                dic.Add(750, "DCCL");
                dic.Add(751, "DCCLI");
                dic.Add(752, "DCCL II");
                dic.Add(753, "DCCL III");
                dic.Add(754, "DCCL IV");
                dic.Add(755, "DCCLV");
                dic.Add(756, "DCCLVI");
                dic.Add(757, "DCCLVII");
                dic.Add(758, "DCCLVIII");
                dic.Add(812, "DCCCXII");
                dic.Add(813, "DCCCXIII");
                dic.Add(814, "DCCCXIV");
                dic.Add(815, "DCCCXV");
                dic.Add(816, "DCCCXVI");
                dic.Add(817, "DCCCXVII");
                dic.Add(818, "DCCCXVIII");
                dic.Add(819, "DCCCXIX");
                dic.Add(820, "DCCCXX");
                dic.Add(821, "DCCCXXI");
                dic.Add(822, "DCCCXXII");
                dic.Add(823, "DCCC XXIII");
                dic.Add(824, "DCCCXXIV");
                dic.Add(825, "DCCCXXV");
                dic.Add(826, "DCCCXXVI");
                dic.Add(827, "DCCCXXVII");
                dic.Add(828, "DCCCXXVIII");
                dic.Add(829, "DCCCXXIX");
                dic.Add(830, "DCCCXXX");
                dic.Add(831, "DCCCXXXI");
                dic.Add(832, "DCCCXXXII");
                dic.Add(833, "DCCCXXXIII");
                dic.Add(834, "DCCCXXXIV");
                dic.Add(835, "DCCCXXXV");
                dic.Add(836, "DCCCXXXVI");
                dic.Add(837, "DCCCXXXVII");
                dic.Add(838, "DCCCXXXVIII");
                dic.Add(839, "DCCCXXXIX");
                dic.Add(840, "DCCCXL");
                dic.Add(841, "DCCCXLI");
                dic.Add(842, "DCCCXLII");
                dic.Add(843, "DCCCXLIII");
                dic.Add(844, "DCCCXLIV");
                dic.Add(845, "DCCCXLV");
                dic.Add(846, "DCCCXLVI");
                dic.Add(847, "DCCCXLVII");
                dic.Add(848, "DCCCXLVIII");
                dic.Add(849, "DCCCXLIX");
                dic.Add(850, "DCCCL");
                dic.Add(851, "DCCCLI");
                dic.Add(852, "DCCCLII");
                dic.Add(853, "DCCCL III");
                dic.Add(854, "DCCCLIV");
                dic.Add(855, "DCCCLV");
                dic.Add(856, "DCCCLVI");
                dic.Add(857, "DCCCLVII");
                dic.Add(858, "DCCCLVIII");
                dic.Add(859, "DCCCLIX");
                dic.Add(860, "DCCCLX");
                dic.Add(861, "DCCCLXI");
                dic.Add(862, "DCCCLXII");
                dic.Add(863, "DCCCLXIII");
                dic.Add(864, "DCCCLXIV");
                dic.Add(865, "DCCCLXV");
                dic.Add(866, "DCCCLXVI");
                dic.Add(867, "DCCCLXVII");
                dic.Add(868, "DCCCLXVIII");
                dic.Add(869, "DCCCLXIX");
                dic.Add(875, "DCCCLXXV");
                dic.Add(876, "DCCCLXXVI");
                dic.Add(877, "DCCCLXXVII");
                dic.Add(878, "DCCCLXXVIII");
                dic.Add(879, "DCCCLXXIX");
                dic.Add(880, "DCCCLXXX");
                dic.Add(881, "DCCCLXXXI");
                dic.Add(882, "DCCCLXXXII");
                dic.Add(883, "DCCCLXXXIII");
                dic.Add(884, "DCCCLXXXIV");
                dic.Add(885, "DCCCLXXXV");
                dic.Add(886, "DCCCLXXXVI");
                dic.Add(887, "DCCCLXXXVII");
                dic.Add(888, "DCCCLXXXVIII");
                dic.Add(889, "DCCCLXXXIX");
                dic.Add(890, "DCCCXC");
                dic.Add(891, "DCCCXCI");
                dic.Add(892, "DCCCXCII");
                dic.Add(893, "DCCCXCIII");
                dic.Add(894, "DCCCXCIV");
                dic.Add(895, "DCCCXCV");
                dic.Add(896, "DCCCXCVI");
                dic.Add(897, "DCCCXCVII");
                dic.Add(898, "DCCCXCVIII");
                dic.Add(899, "DCCCXCIX");
                dic.Add(900, "CM");
                dic.Add(901, "CMI");
                dic.Add(902, "CMII");
                dic.Add(903, "CMIII");
                dic.Add(929, "CMXXIX");
                dic.Add(930, "CMXXX");
                dic.Add(931, "CMXXXI");
                dic.Add(932, "CMXXXII");
                dic.Add(933, "CMXXXIII");
                dic.Add(934, "CMXXXIV");
                dic.Add(935, "CMXXXV");
                dic.Add(936, "CMXXXVI");
                dic.Add(948, "CMXLVIII");
                dic.Add(949, "CMXLIX");
                dic.Add(950, "CML");
                dic.Add(951, "CMLI");
                dic.Add(952, "CMLII");
                dic.Add(953, "CML III");
                dic.Add(954, "CMLIV");
                dic.Add(955, "CMLV");
                dic.Add(956, "CMLVI");
                dic.Add(957, "CMLVII");
                dic.Add(958, "CMLVIII");
                dic.Add(959, "CMLIX");
                dic.Add(960, "CMLX");
                dic.Add(961, "CMLXI");
                dic.Add(962, "CMLXII");
                dic.Add(963, "CMLXIII");
                dic.Add(964, "CMLXIV");
                dic.Add(965, "CMLXV");
                dic.Add(966, "CMLXVI");
                dic.Add(967, "CMLXVII");
                dic.Add(968, "CMLXVIII");
                dic.Add(969, "CMLXIX");
                dic.Add(970, "CMLXX");
                dic.Add(971, "CMLXXI");
                dic.Add(972, "CMLXXII");
                dic.Add(973, "CMLXXIII");
                dic.Add(974, "CMLXXIV");
                dic.Add(975, "CMLXXV");
                dic.Add(976, "CMLXXVI");
                dic.Add(977, "CMLXXVII");
                dic.Add(978, "CMLXXVIII");
                dic.Add(979, "CMLXXIX");
                dic.Add(980, "CMLXXX");
                dic.Add(981, "CMLXXXI");
                dic.Add(982, "CMLXXXII");
                dic.Add(983, "CMLXXXIII");
                dic.Add(984, "CMLXXXIV");
                dic.Add(985, "CMLXXXV");
                dic.Add(986, "CMLXXXVI");
                dic.Add(987, "CMLXXXVII");
                dic.Add(988, "CMLXXXVIII");
                dic.Add(989, "CMLXXXIX");
                dic.Add(990, "CMXC");
                dic.Add(991, "CMXCI");
                dic.Add(992, "CMXCII");
                dic.Add(993, "CMXCIII");
                dic.Add(994, "CMXCIV");
                dic.Add(995, "CMXCV");
                dic.Add(996, "CMXCVI");
                dic.Add(997, "CMXCVII");
                dic.Add(998, "CMXCVIII");
                dic.Add(999, "CMXCIX");
                return dic;
            }
        }

    }
}